version: '3.8'

services:
  angular-app:
    build:
      context: ./appangular
      dockerfile: Dockerfile
    ports:
      - "80:80"
    depends_on:
      - websocket-service

  websocket-service:
    build:
      context: ./websocket-service
      dockerfile: Dockerfile
    ports:
      - "3000:3000"