version: '3.8'

services:
  appangular:
    build:
      context: ./appangular
    container_name: appangular
    ports:
      - "80:80"
    depends_on:
      - websocket-service

  websocket-service:
    build:
      context: ./websocket-service
    ports:
      - "3000:3000"